kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-rest
spec:
  selector:
    matchLabels:
      app: api-rest
      version: v01
  replicas: 2
  template:
    metadata:
      labels:
        app: api-rest
        version: v01
    spec:
      containers:
      - name: api-rest
        image: killgoliat/api-rest:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: api-rest
spec:
  selector:
    app: api-rest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer