kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-rest-deployment
spec:
  selector:
    matchLabels:
      app: api-rest
      version: v01
  replicas: 2
  template:
    metadata:
      labels:
        app: api-rest
        version: v01
    spec:
      containers:
      - name: api-rest-container
        image: killgoliat/api-rest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: api-rest-service
spec:
  selector:
    app: api-rest
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5000