apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest-deployment
spec:
  selector:
    matchLabels:
      app: api-rest
  replicas: 2
  template:
    metadata:
      labels:
        app: api-rest
    spec:
      containers:
      - name: api-rest-container
        image: killgoliat/api-rest
        ports:
        - containerPort: 5000
        resources:
      requests:
        cpu: "250m"
      limits:
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-rest-service
spec:
  selector:
    app: api-rest
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5000