apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest-deployment
spec:
  selector:
    matchLabels:
      app: api-rest
  replicas: 2
  template:
    metadata:
      labels:
        app: api-rest
    spec:
      containers:
      - name: api-rest-container
        image: python
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-rest-service
spec:
  selector:
    app: api-rest
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5000