name: deploy-to-eks

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_ACCESS_TOKEN }
   
    - name: Build and push Docker image
      run: |
        docker tag api-rest:latest ${{ secrets.HUB_USERNAME }}/api-rest:latest
        docker push ${{ secrets.HUB_USERNAME }}/api-rest:latest
 
    #- name: Deploy to EKS
    #  env:
    #    KUBECONFIG: ${{ secrets.KUBECONFIG }}
    #    IMAGE_TAG: ${{ env.IMAGE_TAG }}
    #  run: |
    #    kubectl apply -f deploy.yaml
    #    kubectl set image deployment/api-rest-deployment api-rest-container=$ECR_REGISTRY/api-rest:$IMAGE_TAG


