name: deploy-to-eks

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
        
    - name: Add flask
      run: python -m pip install flask
      
    - name: Add pytest
      run: pip install pytest
      
    - name: Run test
      run: pytest -v  

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Build image
      run: docker build -t api-rest:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_ACCESS_TOKEN }}
   
    - name: Build and push Docker image
      run: |
        docker tag api-rest:latest ${{ secrets.HUB_USERNAME }}/api-rest:latest
        docker push ${{ secrets.HUB_USERNAME }}/api-rest:latest
 
    - name: Deploy to EKS
      env:
        AWS_KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}
      run: |
        aws eks update-kubeconfig --name api-rest-deployment
        envsubst < deploy.yml | kubectl apply -f -
         kubectl get nodes
      #run: | 
      #  aws eks update-kubeconfig --name api-rest-deployment
      #  kubectl apply -f deploy.yml
      # kubectl get nodes
      
        


